FROM nginx:stable-alpine

# author
MAINTAINER  mori

# TimeZoneをAsia/Tokyoに設定する
RUN apk --update add tzdata
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN apk del tzdata

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./conf.d /etc/nginx/conf.d

WORKDIR /var/www/
